export {default as Navbar} from './navbar/navbar'
export {default as Search} from './search/search'
export {default as VideoDetails} from './video-details/video-details'
export {default as Channel} from './channel/channel'
export {default as Mainn} from './main/mainn'
export {default as SearchBar} from './search-bar/search-bar'
export {default as Category} from './category/category'
export {default as Videos} from './videos/video'